export const guides = [
    {   id: '1',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '2',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '3',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '4',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '5',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '6',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '7',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '8',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '9',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '10',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '11',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '12',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '13',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '14',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '15',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '16',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '17',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '18',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    },
    {   id: '19',
        name: 'Titre de jeux',
        image: '../game.jpg',
        avatar: '../new.jpg',
        userName: 'nameofuser',
        time: '1 day ago'
    }
]